import type { QuestionPaper } from "@/lib/demo-data";
import { difficultyLightChip } from "@/lib/difficulty";
import { cn } from "@/lib/utils";

function fmtDuration(mins: number) {
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return m ? `${h} hr ${m} min` : `${h} hours`;
}

export function PaperSheet({
  paper,
  className,
}: {
  paper: QuestionPaper;
  className?: string;
}) {
  return (
    <div
      data-print="paper"
      className={cn(
        "bg-[#f7f6f2] text-[#1b1b20] selection:bg-violet/30",
        className,
      )}
    >
      <div className="mx-auto max-w-3xl px-8 py-10 sm:px-12 sm:py-14">
        <header className="text-center">
          <p className="font-mono text-[0.62rem] uppercase tracking-[0.22em] text-[#8a8a90]">
            {paper.course}
          </p>
          <h3 className="mt-2 text-2xl font-semibold tracking-tight sm:text-[1.7rem]">
            {paper.subject}
          </h3>
          <p className="mt-1 text-sm text-[#6a6a72]">
            {paper.examTitle} · Paper Code {paper.subjectCode}
          </p>
          <div className="mt-5 flex items-center justify-between border-y border-[#dcdbd4] py-2.5 text-[0.78rem] font-medium">
            <span>Duration: {fmtDuration(paper.durationMins)}</span>
            <span>Maximum Marks: {paper.totalMarks}</span>
          </div>
        </header>

        <div className="mt-8 flex flex-col gap-9">
          {paper.sections.map((section) => (
            <section key={section.id} data-print="section">
              <div
                data-print="section-heading"
                className="flex items-baseline justify-between gap-4"
              >
                <h4 className="text-[0.95rem] font-semibold tracking-tight">
                  {section.title}
                </h4>
              </div>
              <p className="mt-0.5 text-[0.78rem] italic text-[#6a6a72]">
                {section.instruction}
              </p>

              <ol className="mt-4 flex flex-col gap-4">
                {section.questions.map((q) => (
                  <li
                    key={q.id}
                    data-print="question"
                    className="flex gap-3.5"
                  >
                    <span className="select-none font-mono text-[0.78rem] font-semibold text-[#52524e]">
                      {q.number}.
                    </span>
                    <div className="min-w-0 flex-1">
                      <p className="text-[0.86rem] leading-relaxed">{q.text}</p>
                      <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
                        <span className="rounded bg-[#ecebe4] px-1.5 py-0.5 font-mono text-[0.58rem] uppercase tracking-wider text-[#6a6a72]">
                          {q.unit}
                        </span>
                        <span
                          className={cn(
                            "rounded px-1.5 py-0.5 font-mono text-[0.58rem] uppercase tracking-wider",
                            difficultyLightChip[q.difficulty],
                          )}
                        >
                          {q.difficulty}
                        </span>
                        <span className="rounded bg-[#ecebe4] px-1.5 py-0.5 font-mono text-[0.58rem] uppercase tracking-wider text-[#6a6a72]">
                          {q.bloom}
                        </span>
                      </div>
                    </div>
                    <span
                      data-print="marks"
                      className="shrink-0 font-mono text-[0.78rem] font-semibold text-[#1b1b20]"
                    >
                      [{q.marks}]
                    </span>
                  </li>
                ))}
              </ol>
            </section>
          ))}
        </div>

        <footer className="mt-10 border-t border-[#dcdbd4] pt-4 text-center font-mono text-[0.62rem] uppercase tracking-[0.2em] text-[#a0a09a]">
          End of Question Paper · Generated by QraftPaper
        </footer>
      </div>
    </div>
  );
}
