import type { Metadata } from "next";
import { LegalPage, LegalSection } from "@/components/legal/legal-page";
import { supportEmail } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service — QraftPaper",
  description:
    "The terms that govern your use of QraftPaper, including accounts, billing, the no-refund policy, AI-output disclaimers, acceptable use and liability.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <LegalPage eyebrow="Legal" title="Terms of Service" updated="May 2026">
      <LegalSection heading="1. Acceptance of these terms">
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and
          use of QraftPaper (the &quot;Service&quot;), operated by Aniket
          Kumbhar (&quot;we&quot;, &quot;us&quot;). By creating an account or using
          the Service you agree to these Terms. If you are using the Service on
          behalf of an institution, you confirm you are authorised to bind that
          institution to these Terms.
        </p>
      </LegalSection>

      <LegalSection heading="2. The service">
        <p>
          QraftPaper uses artificial intelligence to generate draft question
          papers and quizzes from the source material you provide. All output is
          a <strong className="text-fg">draft for educator review</strong>, not a
          finished examination.
        </p>
      </LegalSection>

      <LegalSection heading="3. AI-generated content — no guarantee of accuracy">
        <p>
          Questions and papers produced by the Service are generated by AI and
          are <strong className="text-fg">not guaranteed to be accurate,
          complete, correct, original, or free of errors</strong>. Output may
          contain mistakes, ambiguous or out-of-syllabus questions, or repeated
          content.
        </p>
        <p>
          Generated papers are{" "}
          <strong className="text-fg">not the same as, and are not a
          substitute for, official or real examination papers</strong>, and may
          differ in difficulty, coverage, phrasing and correctness. You are
          solely responsible for reviewing, verifying, editing and approving any
          output before using it in an assessment. We are not liable for any
          consequences arising from reliance on generated content, including
          errors that reach an examination.
        </p>
      </LegalSection>

      <LegalSection heading="4. Accounts & eligibility">
        <p>
          The Service is intended for educational institutions and their
          authorised staff. You are responsible for the confidentiality of your
          credentials and for all activity under your account, and must notify us
          promptly of any unauthorised access.
        </p>
      </LegalSection>

      <LegalSection heading="5. Billing & no-refund policy">
        <p>
          QraftPaper is a paid platform with no free tier. Subscriptions are
          billed in advance through our payment processor and renew automatically
          for the same period unless cancelled before the renewal date. You may
          cancel at any time; cancellation stops future charges and your access
          continues until the end of the paid period.
        </p>
        <p>
          <strong className="text-fg">All purchases are final and
          non-refundable.</strong> We do not provide refunds, credits or
          pro-rated reimbursements for any purchase, subscription period,
          unused time, or partial use, except where a refund is strictly
          required by applicable law. Prices may change with notice to workspace
          owners, effective from the next renewal. Fees are exclusive of taxes,
          which are your responsibility where applicable.
        </p>
      </LegalSection>

      <LegalSection heading="6. Your content & responsibilities">
        <p>
          You retain ownership of the material you upload (syllabi, sample
          papers, previous-year papers) and of the papers you generate. You
          represent and warrant that you{" "}
          <strong className="text-fg">have all necessary rights and permissions
          to upload that material</strong> and that doing so does not infringe
          any third party&apos;s intellectual property or other rights.
        </p>
        <p>
          You grant us a limited, non-exclusive licence to host and process your
          material solely to operate the Service for you.
        </p>
      </LegalSection>

      <LegalSection heading="7. Acceptable use">
        <p>
          You agree not to: misuse, disrupt, reverse-engineer or overload the
          Service; upload unlawful material or material you lack rights to; use
          the Service to violate academic-integrity rules or applicable law; or
          resell or share access outside your licensed workspace.
        </p>
      </LegalSection>

      <LegalSection heading="8. Intellectual property">
        <p>
          QraftPaper, including its software, design and branding, is owned by us
          and protected by intellectual-property laws. These Terms grant you no
          rights to the platform itself other than the right to use it under your
          subscription.
        </p>
      </LegalSection>

      <LegalSection heading="9. Third-party services">
        <p>
          The Service relies on third-party providers for AI generation,
          hosting, data storage and payments. Your use may be subject to their
          terms, and content necessary to perform a request may be shared with
          them solely to provide the Service. See our{" "}
          <a
            className="text-accent transition-colors hover:text-accent-soft"
            href="/privacy"
          >
            Privacy Policy
          </a>
          .
        </p>
      </LegalSection>

      <LegalSection heading="10. Suspension & termination">
        <p>
          We may suspend or terminate access for breach of these Terms,
          non-payment, or to protect the Service or other users. You may stop
          using the Service at any time; sections that by their nature should
          survive termination (e.g. payment, disclaimers, liability) will
          continue to apply.
        </p>
      </LegalSection>

      <LegalSection heading="11. Disclaimer of warranties">
        <p>
          The Service is provided <strong className="text-fg">&quot;as is&quot;
          and &quot;as available&quot;</strong> without warranties of any kind,
          express or implied, including merchantability, fitness for a particular
          purpose, accuracy, or uninterrupted availability. We do not warrant
          that the Service will be error-free or that output will meet your
          requirements.
        </p>
      </LegalSection>

      <LegalSection heading="12. Limitation of liability">
        <p>
          To the maximum extent permitted by law, we are not liable for any
          indirect, incidental, special or consequential damages, or for loss of
          data, reputation or opportunity. Our total liability for any claim is
          limited to the amount you paid for the Service in the three months
          before the event giving rise to the claim.
        </p>
      </LegalSection>

      <LegalSection heading="13. Indemnification">
        <p>
          You agree to indemnify and hold us harmless from claims arising out of
          your material, your use of the Service, or your breach of these Terms,
          including claims that your uploaded material infringes a third
          party&apos;s rights.
        </p>
      </LegalSection>

      <LegalSection heading="14. Governing law">
        <p>
          These Terms are governed by the laws of India, and any dispute will be
          subject to the exclusive jurisdiction of the courts of Maharashtra,
          India.
        </p>
      </LegalSection>

      <LegalSection heading="15. Changes & contact">
        <p>
          We may update these Terms; material changes will be communicated to
          workspace owners and take effect on the date stated. Continued use
          after changes constitutes acceptance. Questions? Email{" "}
          <a
            className="text-accent transition-colors hover:text-accent-soft"
            href={`mailto:${supportEmail}`}
          >
            {supportEmail}
          </a>
          .
        </p>
      </LegalSection>
    </LegalPage>
  );
}
