import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ListChecks, Sparkles } from "lucide-react";

import { Logo } from "@/components/logo";
import { QuizRunner } from "@/components/quiz-runner";
import { GlowButton } from "@/components/ui/glow-button";
import { exampleQuiz } from "@/lib/demo-data";

export const metadata: Metadata = {
  title: "Sample MCQ quiz — QraftPaper",
  description:
    "Try a real QraftPaper-generated MCQ quiz with timer + scoring. No signup required.",
};

export const runtime = "nodejs";

/**
 * Public-facing demo quiz that runs entirely off the in-memory `exampleQuiz`.
 * No DB row required — this is the "try before signup" path linked from the
 * empty dashboard and from the landing page footer.
 *
 * The QuizRunner is reused as-is; we just strip the answer key client-side
 * the same way /take/[id] does and skip the grade-via-API plumbing (the demo
 * has its answer key inline, no need to hit the server).
 */
export default function DemoQuizPage() {
  const safeQuiz = {
    ...exampleQuiz,
    questions: exampleQuiz.questions.map((q) => ({
      id: q.id,
      prompt: q.prompt,
      options: q.options,
      unit: q.unit,
      difficulty: q.difficulty,
      // Inline correctness so the runner doesn't need a /grade endpoint —
      // for the demo we accept the risk that a curious developer can read
      // the answers in DevTools. It's a demo, not a graded exam.
      correctIndex: q.correctIndex,
      explanation: q.explanation,
    })),
  };

  return (
    <div className="min-h-screen">
      <header className="sticky top-0 z-30 border-b border-line bg-canvas/85 backdrop-blur-md">
        <div className="mx-auto flex max-w-3xl items-center justify-between gap-3 px-5 py-3.5 sm:px-8">
          <Logo />
          <GlowButton href="/signup" size="sm">
            <Sparkles className="h-3.5 w-3.5" />
            Build your own
          </GlowButton>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-5 py-8 sm:px-8">
        <div className="mb-6">
          <p className="flex items-center gap-2 font-mono text-[0.66rem] uppercase tracking-[0.2em] text-violet-bright">
            <ListChecks className="h-3.5 w-3.5" />
            Sample QraftPaper quiz
          </p>
          <h1 className="mt-2 text-2xl font-semibold tracking-tight text-gradient sm:text-3xl">
            {exampleQuiz.title}
          </h1>
          <p className="mt-1.5 text-sm text-fg-muted">
            {exampleQuiz.subjectCode} · {exampleQuiz.questions.length} questions
            · {exampleQuiz.durationMins} min · instant scoring
          </p>
        </div>

        <QuizRunner
          quiz={safeQuiz}
          backHref="/signup"
          backLabel="Build your own quiz"
        />

        <div className="mt-8 flex flex-col items-center gap-3 rounded-2xl glass p-6 text-center">
          <p className="text-sm text-fg-muted">
            This quiz was generated by QraftPaper from a real DSA syllabus and
            past papers.
          </p>
          <GlowButton href="/signup" size="md">
            Generate quizzes from your own syllabus
            <ArrowRight className="h-4 w-4" />
          </GlowButton>
          <Link
            href="/#how"
            className="text-[0.78rem] text-fg-muted underline-offset-2 transition-colors hover:text-fg hover:underline"
          >
            How does it work?
          </Link>
        </div>
      </main>
    </div>
  );
}
